"""
Generate LP with forced assignments and symbolic labels, then analyze.
"""
import sys, os, json
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from heu180h import MILP_Sheduler
from pyomo.environ import *

data = json.load(open('inputsABCD/ABCD_multi_check_test.json'))
intended = {data['Flights'][i][0]: next(j for j,c in enumerate(data['Cost_Matrix'][i]) if c==1000.0)
            for i in range(len(data['Flights']))}

sched = MILP_Sheduler('inputsABCD/ABCD_multi_check_test.json')
m = sched.build_model(use_check_hierarchy=False)

# Force x variables to intended
m.c_forced = ConstraintList()
for fid, j in intended.items():
    for j2 in range(5):
        if j2 == j:
            m.c_forced.add(m.x[fid, j2] == 1)
        else:
            m.c_forced.add(m.x[fid, j2] == 0)

# Write LP with symbolic labels
m.write('debug_forced.lp', io_options={'symbolic_solver_labels': True})
print("Written debug_forced.lp")

# Count what c12days generates for D-check
print("\n=== c12days D-check constraints ===")
ival = 2  # D-check dur_days
days = sorted(sched.days)
fm_flights = sched.maint_flight_ids
flight_data = sched.flight_data

for fid in fm_flights:
    days_i = flight_data[fid]['day_arrival']
    forced = range(days_i+1, min(days_i+ival, days[-1]+1))
    zero_after = range(days_i+ival, days[-1]+1)
    if list(forced):
        print(f"  F{fid} (day_arr={days_i}): z[{fid},j,{list(forced)[0]},D] == z[{fid},j,{days_i},D]  for all j")

# CRITICAL: does c9 force something with c12days?
# c9: x[i,j] >= z[i,j,d,c] for ALL d
# c12days forces z[i,j,d2,D] == z[i,j,d_arr,D]
# Combined: x[i,j] >= z[i,j,d_arr,D]  (that's fine, c9 already does this for d=d_arr)

# But what about c15 + c12days?
# c15: mega[j,d,c] + x[i2,j] <= 1 for d != d_arr(i)
# c12days: z[i,j,d2,D] == z[i,j,d_arr,D] => y[j,d2,D] = sum z = 1 => mega[j,d2,D]=1
# c15: mega[j,d2,D] + x[i2,j] <= 1 for i2 departing from C in window [arr_i, arr_i+dur]

print("\n=== c15 constraints generated by D-check via c12days days ===")
check_dur = sched.check_dur
for fid in fm_flights:
    days_i = flight_data[fid]['day_arrival']
    arr = flight_data[fid]['arrivalTime']
    apt = flight_data[fid]['destination']
    if apt != 'C': continue
    
    dur = check_dur['D']
    # What flights are in window [arr, arr+dur] departing from C?
    blocked = [(f2, flight_data[f2]['departureTime'], flight_data[f2]['day_departure'])
               for f2 in flight_data
               if flight_data[f2]['origin'] == 'C'
               and arr <= flight_data[f2]['departureTime'] <= arr + dur]
    
    # c12days forces mega[j,d2,D]=1 for d2 in (days_i, days_i+2)
    forced_days = list(range(days_i+1, min(days_i+2, days[-1]+1)))
    
    for d2 in forced_days:
        # c15 for d2 != days_i: mega[j,d2,D] + x[i2,j] <= 1 
        # mega[j,d2,D] = 1 (forced) => x[i2,j] = 0 for all i2 in blocked
        blocked_on_d2 = [(f2,d,t) for f2,t,d in blocked if d == d2]
        if blocked_on_d2:
            print(f"  F{fid} D-check: On day {d2} (forced by c12days), mega[j,{d2},D]=1 BLOCKS flights:")
            for f2,d2_,t2 in blocked_on_d2:
                ac_intended = intended.get(f2, '?')
                print(f"    F{f2} dep={t2} (intended AC{ac_intended}) -> x[{f2},AC]=0! If AC{ac_intended} intended, CONFLICT!")
